import * as path from 'path';
import { AiRunner, AiRunnerResult } from '../../application/ports/ai-runner';
import { COVERAGE_FILE_FORMAT_EXAMPLE, execToString } from '@utils';
import { execa } from 'execa';

export class SimpleAiRunner implements AiRunner {

  model: string;
  
  constructor() {
    //OpenAIConfig.initialize();
    this.model = 'gpt-5.1-codex'
  }

  private getNewPrBranchName(file: string): string {
    const branchFriendlyFileName = path.basename(file, '.ts').replace(/\W+/g, '-').toLowerCase();
    const branchFriendlyDateName = new Date().toISOString().replace(/[^\w-]/g,'-');
    return `tci--${branchFriendlyFileName}--${branchFriendlyDateName}`;
  }

  private getNewPrTitle(file: string): string {
    return `Improve test coverage for ${file}`;
  }

  private getNewPrBody(file: string): string {
    return 'Automatically generated by ts-coverage-improver/codex'
  }

  getNewPrInfo(file: string) {
    return {
      branch: this.getNewPrBranchName(file),
      title: this.getNewPrTitle(file),
      body: this.getNewPrBody(file),
    }
  }


  async run(params: {
    repoPath: string, 
    filePath: string, 
    owner: string,
    repo: string
  }): Promise<AiRunnerResult> {
    const { repoPath, filePath, owner, repo } = params;
    const prInfo = this.getNewPrInfo(filePath);
    const { branch: prBranch, title: prTitle, body: prBody } = prInfo;
    const prompt = `Improve test coverage for the file ${filePath}.`
      + 'Please writing unit tests (*.test.ts) or integration tests (*.spec.ts), and commit then on the current branch. '
      + `The commit message should be name 'ts-coverage-improver: Improved test coverage for ${filePath}'. \n`
      + 'If one does not already exist, please also create a file named "ts-coverage-improver.json" in the repository root directory with the format:'
      + `\n\n${JSON.stringify(COVERAGE_FILE_FORMAT_EXAMPLE, null, 2)}\n\n`
      + 'If a coverage scanner package is already installed in the repository, please use that. Otherwise, please install one, and use '
      + 'that to measure the coverage percentage for that file after adding your tests, which should be stored in the json file mentioned above. '
      + 'Finally, please run a build and lint (check the package.json/README for the exact command) before committing your changes'
      + ` and pushing them.` 

      const prompt2 = `TEST.`
      + 'Please make one minimal change to any file in this repository, without changing any existiong functionality, config, or tests. '
      + 'Ideally make the change to a non-code file such as README.md, or similar. '
      + 'Under NO circumstance should you install any dependencies or mess around with any low level crap. Just make a minimal change and exit.'
      // + 'If one does not already exist, please also create a file named "ts-coverage-improver.json" in the repository root directory with the format:'
      // + `\n\n${JSON.stringify(COVERAGE_FILE_FORMAT_EXAMPLE, null, 2)}\n\n`
      // + 'If a coverage scanner package is already installed in the repository, please use that. Otherwise, please install one, and use '
      // + 'that to measure the coverage percentage for that file after adding your tests, which should be stored in the json file mentioned above. '

    try {
      console.info("Preparing to run")
      const baseBranch = execToString("git rev-parse --abbrev-ref HEAD", repoPath);
      await execa('git', ['checkout', '-b', prBranch], { cwd: repoPath });
      const newBranch = execToString("git rev-parse --abbrev-ref HEAD", repoPath);
      console.info(`Created and switched to new branch ${newBranch}`);
      console.info("Running codex command")
      await execa('codex', ['--cd', repoPath, 'exec', '--yolo', prompt2], {
        cwd: repoPath,
        stdio: 'inherit',
      });
      console.info("finished running")
      await execa('git', ['add', '-A'], { cwd: repoPath });
      await execa('git', ['commit', '-m', 'minimal test change'], { cwd: repoPath });
      await execa('git', ['push', '-u', 'origin', prBranch], { cwd: repoPath });
      await execa('gh', ['pr', 'create', '--title', prTitle, '--body', prBody, '--head', prBranch, '--base', baseBranch], { cwd: repoPath });
      const prsList = execToString(`gh pr list --head "${prBranch}" --json url,headRefName --limit 1`, repoPath);
      const prsListJson = JSON.parse(prsList) as [{ url: string; headRefName: string }];
      if (!prsListJson.length || prsListJson[0].headRefName !== prBranch) {
        console.error("PR not found from: ", prsListJson);
        throw new Error("PR not found");
      }
      const prUrl = prsListJson[0].url;
      console.info("PR created at ", prUrl);
      await execa('git', ['checkout', baseBranch], { cwd: repoPath });
      return { success: true, output: prUrl };
    } catch (err: any) {
      console.error("Error", err);
      return {
        success: false,
        output: 'Job failed'
      };
    }
  }
}
